// Generated by gencpp from file learn_ball/ballCor.msg
// DO NOT EDIT!


#ifndef LEARN_BALL_MESSAGE_BALLCOR_H
#define LEARN_BALL_MESSAGE_BALLCOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_ball
{
template <class ContainerAllocator>
struct ballCor_
{
  typedef ballCor_<ContainerAllocator> Type;

  ballCor_()
    : heading()
    , color()
    , x(0)
    , y(0)
    , radius(0)
    , upperH(0)
    , upperS(0)
    , upperV(0)
    , lowerH(0)
    , lowerS(0)
    , lowerV(0)  {
    }
  ballCor_(const ContainerAllocator& _alloc)
    : heading(_alloc)
    , color(_alloc)
    , x(0)
    , y(0)
    , radius(0)
    , upperH(0)
    , upperS(0)
    , upperV(0)
    , lowerH(0)
    , lowerS(0)
    , lowerV(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _heading_type;
  _heading_type heading;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _radius_type;
  _radius_type radius;

   typedef int64_t _upperH_type;
  _upperH_type upperH;

   typedef int64_t _upperS_type;
  _upperS_type upperS;

   typedef int64_t _upperV_type;
  _upperV_type upperV;

   typedef int64_t _lowerH_type;
  _lowerH_type lowerH;

   typedef int64_t _lowerS_type;
  _lowerS_type lowerS;

   typedef int64_t _lowerV_type;
  _lowerV_type lowerV;




  typedef boost::shared_ptr< ::learn_ball::ballCor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_ball::ballCor_<ContainerAllocator> const> ConstPtr;

}; // struct ballCor_

typedef ::learn_ball::ballCor_<std::allocator<void> > ballCor;

typedef boost::shared_ptr< ::learn_ball::ballCor > ballCorPtr;
typedef boost::shared_ptr< ::learn_ball::ballCor const> ballCorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_ball::ballCor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_ball::ballCor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learn_ball

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'learn_ball': ['/home/pi/catkin_ws/src/learn_ball/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learn_ball::ballCor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_ball::ballCor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_ball::ballCor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_ball::ballCor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_ball::ballCor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_ball::ballCor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_ball::ballCor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a81fb488530784a24d84e3f7199f24f6";
  }

  static const char* value(const ::learn_ball::ballCor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa81fb488530784a2ULL;
  static const uint64_t static_value2 = 0x4d84e3f7199f24f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_ball::ballCor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_ball/ballCor";
  }

  static const char* value(const ::learn_ball::ballCor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_ball::ballCor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string heading\n\
string color\n\
int64 x\n\
int64 y\n\
int64 radius\n\
int64 upperH\n\
int64 upperS\n\
int64 upperV\n\
int64 lowerH\n\
int64 lowerS\n\
int64 lowerV\n\
";
  }

  static const char* value(const ::learn_ball::ballCor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_ball::ballCor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.color);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
      stream.next(m.upperH);
      stream.next(m.upperS);
      stream.next(m.upperV);
      stream.next(m.lowerH);
      stream.next(m.lowerS);
      stream.next(m.lowerV);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ballCor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_ball::ballCor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_ball::ballCor_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.heading);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<int64_t>::stream(s, indent + "  ", v.radius);
    s << indent << "upperH: ";
    Printer<int64_t>::stream(s, indent + "  ", v.upperH);
    s << indent << "upperS: ";
    Printer<int64_t>::stream(s, indent + "  ", v.upperS);
    s << indent << "upperV: ";
    Printer<int64_t>::stream(s, indent + "  ", v.upperV);
    s << indent << "lowerH: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lowerH);
    s << indent << "lowerS: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lowerS);
    s << indent << "lowerV: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lowerV);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_BALL_MESSAGE_BALLCOR_H
